//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8806
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace SophisETL.Transform.ComputeOffsetNAV.Xml
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/ComputeOffsetNAV")]
    [System.Xml.Serialization.XmlRootAttribute("settings", Namespace="http://www.sophis.net/SophisETL/Transform/ComputeOffsetNAV", IsNullable=false)]
    public partial class Settings
    {

        private ComputeElement[] ComputeListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComputeList")]
        public ComputeElement[] ComputeList
        {
            get
            {
                return this.ComputeListField;
            }
            set
            {
                this.ComputeListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sophis.net/SophisETL/Transform/ComputeOffsetNAV")]
    public partial class ComputeElement
    {

        private string groupByFieldField;

        private string computeFieldField;

        private string computeNameField;

        /// <remarks/>
        public string groupByField
        {
            get
            {
                return this.groupByFieldField;
            }
            set
            {
                this.groupByFieldField = value;
            }
        }

        /// <remarks/>
        public string computeField
        {
            get
            {
                return this.computeFieldField;
            }
            set
            {
                this.computeFieldField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string computeFieldName
        {
            get
            {
                return this.computeNameField;
            }
            set
            {
                this.computeNameField = value;
            }
        }
    }
}
