CREATE TABLE DTS(
    ID NUMBER(10) NOT NULL,
    TRANS_NAME VARCHAR2(250 BYTE),
    TRANS_TYPE VARCHAR2(30 BYTE),
    START_TIME DATE,
    END_TIME DATE,
    DURATION VARCHAR2(8),
    TOTAL_LINES INTEGER,
    PROCESSED_LINES INTEGER,
    FAILURE_LINES INTEGER,
    INPUT_FILE VARCHAR(1000 BYTE),
    OUTPUT_FILE VARCHAR(1000 BYTE),
    FAILURE_FILE VARCHAR(1000 BYTE),
    INFO VARCHAR2(4000 BYTE),
    CONSTRAINT DTS_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE DTS_SEQ
    START WITH     100000
    INCREMENT BY   1
    NOCACHE
    NOCYCLE;
