--{{SOPHIS_SQL (do not delete this line)

CREATE TABLE MEDIO_FXAUTO_MARKETS (
    CODE VARCHAR2(5) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    ACTIVE NUMBER(1) NOT NULL,
    CONSTRAINT MEDIO_FXAUTO_MARKETS_PK PRIMARY KEY (CODE),
    CONSTRAINT MEDIO_FXAUTO_MARKETS_ACTIVE CHECK (ACTIVE IN (1, 0))
);

INSERT INTO MEDIO_FXAUTO_MARKETS VALUES('EU', 'European Market', 1);
INSERT INTO MEDIO_FXAUTO_MARKETS VALUES('US', 'US Market', 1);
INSERT INTO MEDIO_FXAUTO_MARKETS VALUES('OT', 'Asian, Mid East, Australian Markets', 1);

CREATE TABLE MEDIO_FXAUTO_CURRENCIES (
    MARKET VARCHAR2(5) NOT NULL,
    CODE VARCHAR2(3) NOT NULL,
    CONSTRAINT MEDIO_FXAUTO_CURRENCIES_PK PRIMARY KEY (MARKET, CODE)
);

INSERT INTO MEDIO_FXAUTO_CURRENCIES VALUES('EU', 'EUR');
INSERT INTO MEDIO_FXAUTO_CURRENCIES VALUES('EU', 'GBP');
INSERT INTO MEDIO_FXAUTO_CURRENCIES VALUES('EU', 'NOK');
INSERT INTO MEDIO_FXAUTO_CURRENCIES VALUES('EU', 'DKK');
INSERT INTO MEDIO_FXAUTO_CURRENCIES VALUES('EU', 'CHF');
INSERT INTO MEDIO_FXAUTO_CURRENCIES VALUES('US', 'USD');
INSERT INTO MEDIO_FXAUTO_CURRENCIES VALUES('US', 'CAD');
INSERT INTO MEDIO_FXAUTO_CURRENCIES VALUES('OT', 'AUD');
INSERT INTO MEDIO_FXAUTO_CURRENCIES VALUES('OT', 'JPY');

--CREATE TABLE MEDIO_FXAUTO_SLEEVES (
--    FUND_ID NUMBER(10) NOT NULL,
--    IDENT NUMBER(10) NOT NULL,
--    CONSTRAINT MEDIO_FXAUTO_SLEEVES_PK PRIMARY KEY (IDENT)
--);

CREATE TABLE MEDIO_FXAUTO_SLEEVES (
    IDENT NUMBER(10) NOT NULL,
    CCY CHAR(3),
    BPS NUMBER(3),
    THRESHOLD NUMBER,
    CONSTRAINT MEDIO_FXAUTO_SLEEVES_PK PRIMARY KEY (IDENT)
);

CREATE GLOBAL TEMPORARY TABLE MEDIO_FX_SLEEVES (
	PARENTID VARCHAR2(40),
	ID VARCHAR2(40) NOT NULL,
    NAME VARCHAR2(40),
    BALANCE NUMBER,
    CURRENCY CHAR(3),
    BPS NUMBER(3),
    THRESHOLD NUMBER,
    AMOUNT NUMBER,
    WEIGHTNAV NUMBER,
    DATESETTLEMENT DATE,
    NODETYPE NUMBER(2) NOT NULL,
	CONSTRAINT MEDIO_FX_SLEEVES_UQ UNIQUE (PARENTID, ID, DATESETTLEMENT)
)
ON COMMIT PRESERVE ROWS
NOCACHE;

CREATE GLOBAL TEMPORARY TABLE MEDIO_VALUES (
	VALSTR VARCHAR2(40),
	VALNUM NUMBER,
	VALNUM2 NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE;

--}}SOPHIS_SQL