--{{SOPHIS_SQL (do not delete this line)

DROP TABLE MEDIO_FXAUTO_CURRENCIES;
DROP TABLE MEDIO_FXAUTO_MARKETS;
DROP TABLE MEDIO_FXAUTO_SLEEVES;
DROP TABLE MEDIO_FX_SLEEVES;
DROP TABLE MEDIO_VALUES;

--}}SOPHIS_SQL