CREATE TABLE "EMAFI_RECO_RELEV_BANC" 
(
	"TYPE_ENREG" VARCHAR2(2 BYTE), 
	"CODE_BANQ" VARCHAR2(10 BYTE), 
	"CODE_OPE" VARCHAR2(10 BYTE), 
	"CODE_GUICHET" VARCHAR2(10 BYTE), 
	"CODE_DEV" VARCHAR2(10 BYTE), 
	"NBR_DECIM" NUMBER(1,0), 
	"NUM_COMPTE" VARCHAR2(20 BYTE), 
	"CODE_OPER_INTERB" VARCHAR2(2 BYTE), 
	"DATE_OPERATION" VARCHAR2(6 BYTE), 
	"DATE_VALEUR" VARCHAR2(6 BYTE), 
	"LIBELLE" VARCHAR2(50 BYTE), 
	"NUMERO_ECRIT" VARCHAR2(7 BYTE), 
	"MONTANT" VARCHAR2(15 BYTE), 
	"REFER_1" VARCHAR2(20 BYTE), 
	"NOM_FICHIER" VARCHAR2(50 BYTE), 
	"REFER_FI" NUMBER, 
	"STATUT" VARCHAR2(2 BYTE), 
	"MOTIF_REJET" VARCHAR2(10 BYTE), 
	"ORIGINAL_DATA" VARCHAR2(121 BYTE), 
	"LINE_NUMBER" NUMBER, 
	"MONTANT_NUMBER" NUMBER
)
   
ALTER TABLE RECON_EXTERNAL_BALANCES
ADD TKT_EXTERNAL_ACCOUNT VARCHAR(50);

ALTER TABLE RECON_EXTERNAL_TRADES
ADD TKT_EXTERNAL_ACCOUNT VARCHAR(50);

delete from EMAFI_PARAMETRAGE a where a.categorie = 'Recon_Motif';

Insert into EMAFI_PARAMETRAGE (CATEGORIE,CODE,DESCRIPTION,ORDRE) values ('Recon_Motif','M00','Longueur fichier invalide',1);
Insert into EMAFI_PARAMETRAGE (CATEGORIE,CODE,DESCRIPTION,ORDRE) values ('Recon_Motif','M01','Type enregistrement invalide',2);
Insert into EMAFI_PARAMETRAGE (CATEGORIE,CODE,DESCRIPTION,ORDRE) values ('Recon_Motif','M02','Date opération invalide',3);
Insert into EMAFI_PARAMETRAGE (CATEGORIE,CODE,DESCRIPTION,ORDRE) values ('Recon_Motif','M03','Date valeur invalide',4);
Insert into EMAFI_PARAMETRAGE (CATEGORIE,CODE,DESCRIPTION,ORDRE) values ('Recon_Motif','M04','Soldes et mouvements incohérents',5);
Insert into EMAFI_PARAMETRAGE (CATEGORIE,CODE,DESCRIPTION,ORDRE) values ('Recon_Motif','M99','Autres',6);
