//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace SophisETL.Extract.CSVExtract.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Extract/CSVExtract")]
    [System.Xml.Serialization.XmlRootAttribute("settings", Namespace="http://www.sophis.net/SophisETL/Extract/CSVExtract", IsNullable=false)]
    public partial class Settings {
        
        private string inputFileField;
        
        private string separatorField;
        
        private string escapeField;
        
        private int skipLineField;
        
        private bool skipLineFieldSpecified;
        
        private int headerLineField;
        
        private bool headerLineFieldSpecified;
        
        private CsvField[] csvFieldsField;
        
        /// <remarks/>
        public string inputFile {
            get {
                return this.inputFileField;
            }
            set {
                this.inputFileField = value;
            }
        }
        
        /// <remarks/>
        public string separator {
            get {
                return this.separatorField;
            }
            set {
                this.separatorField = value;
            }
        }
        
        /// <remarks/>
        public string escape {
            get {
                return this.escapeField;
            }
            set {
                this.escapeField = value;
            }
        }
        
        /// <remarks/>
        public int skipLine {
            get {
                return this.skipLineField;
            }
            set {
                this.skipLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skipLineSpecified {
            get {
                return this.skipLineFieldSpecified;
            }
            set {
                this.skipLineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int headerLine {
            get {
                return this.headerLineField;
            }
            set {
                this.headerLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool headerLineSpecified {
            get {
                return this.headerLineFieldSpecified;
            }
            set {
                this.headerLineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable=false)]
        public CsvField[] csvFields {
            get {
                return this.csvFieldsField;
            }
            set {
                this.csvFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Extract/CSVExtract")]
    public partial class CsvField {
        
        private string xmlFieldNameField;
        
        private CsvFieldTypeEnum xmlFieldTypeField;
        
        private string xmlFieldTypeComplementField;
        
        private bool nullableField;
        
        private string separatorField;
        
        private int positionField;
        
        public CsvField() {
            this.nullableField = false;
            this.separatorField = "";
        }
        
        /// <remarks/>
        public string xmlFieldName {
            get {
                return this.xmlFieldNameField;
            }
            set {
                this.xmlFieldNameField = value;
            }
        }
        
        /// <remarks/>
        public CsvFieldTypeEnum xmlFieldType {
            get {
                return this.xmlFieldTypeField;
            }
            set {
                this.xmlFieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public string xmlFieldTypeComplement {
            get {
                return this.xmlFieldTypeComplementField;
            }
            set {
                this.xmlFieldTypeComplementField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool nullable {
            get {
                return this.nullableField;
            }
            set {
                this.nullableField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string separator {
            get {
                return this.separatorField;
            }
            set {
                this.separatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Extract/CSVExtract")]
    public enum CsvFieldTypeEnum {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        DateType,
        
        /// <remarks/>
        DateDDMMYYYY,
        
        /// <remarks/>
        DateDDMMMYYYY,
        
        /// <remarks/>
        DateYYYYMMDD,
        
        /// <remarks/>
        TimeDouble,
    }
}
