SET COLSEP '    '
SET trimout OFF 
SET FEEDBACK OFF
SET heading OFF 
SET verify OFF
SET space 0 
SET NEWPAGE 0 
SET PAGESIZE 0 
SET trimspool ON

SET WRAP OFF
SET TRIMOUT OFF 
SET COLSEP ';'
SET LINESIZE 2000
SET ESCAPE '\'

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ', ';

-- TTF declaration --> send to CACEIS
spool '&2';

SELECT 173 || ';' || 'D' || ';' ||
    (NVL((SELECT SUM(TTF_AMOUNT) FROM 
        (SELECT ID_GROUP, SUM(TTF_AMOUNT) TTF_AMOUNT FROM
            (SELECT DISTINCT TA.SOUSSECTION, TA.ID_GROUP, TA.TTF_AMOUNT
            FROM NATIXIS_TTF_AUDIT TA
            WHERE STATUS_REPORT = 1)
        GROUP BY ID_GROUP)), 0) +
    NVL((SELECT SUM(TTF_AMOUNT) FROM NATIXIS_TTFCOLLECTED_AUDIT WHERE STATUS_REPORT = 1), 0)) || ';' ||
    (NVL((SELECT COUNT(*) FROM 
        (SELECT ID_GROUP, SUM(TTF_AMOUNT) TTF_AMOUNT FROM
            (SELECT DISTINCT TA.SOUSSECTION, TA.ID_GROUP, TA.TTF_AMOUNT
            FROM NATIXIS_TTF_AUDIT TA
            WHERE STATUS_REPORT = 1)
        GROUP BY ID_GROUP)), 0) +
    NVL((SELECT COUNT(*) FROM NATIXIS_TTFCOLLECTED_AUDIT WHERE STATUS_REPORT = 1), 0)) ||
    ';' || TO_CHAR(to_date('&1', 'YYYYMMDD'), 'YYYYMMDD') || ';' || 
    TO_CHAR(ADD_MONTHS(TRUNC(to_date('&1', 'YYYYMMDD'), 'MM'), 1), 'YYYYMM') || ';' || 'NATIXIS_TTF_' || TO_CHAR(to_date('&1', 'YYYYMMDD'), 'YYYYMMDD') || ';' || 'NATXFRPPMAR' || ';' || 
    'NATIXIS' || ';' || '30 AVENUE PIERRE MENDES-FRANCE - 75013 PARIS' || ';' || 'FRA' || ';' || 'FR73542044524'
FROM DUAL;

SELECT ROWNUM || ';' || T.ALL_COLUMN FROM (
SELECT TG.ID, TG.ID || ';' || 'S' || ';' || 'Y' || ';' || TG.ISIN || ';' || TO_CHAR(TG.DATE_NEG, 'YYYYMMDD') || ';' || TO_CHAR(TG.DATE_VAL, 'YYYYMMDD') || ';' || 
    TG.PNA_GROUP || ';' || TA.QTY_UNIT || ';' || SUM(TA.TAXABLE_AMOUNT) || ';' || 
    CASE WHEN TG.EXONERATION = 0 OR TG.EXONERATION IS NULL THEN 'Y' ELSE 'N' END || ';' || 
    CASE WHEN TG.EXONERATION = 0 OR TG.EXONERATION IS NULL THEN ' ' ELSE TO_CHAR(TG.EXONERATION) END || ';' || 
    CASE WHEN TG.EXONERATION IS NOT NULL AND TG.EXONERATION != 0 THEN 0 ELSE SUM(TA.TTF_AMOUNT) END || ';' || 
    'MULT' || ';' || NULL ALL_COLUMN
FROM
    (SELECT DISTINCT SOUSSECTION, ID_GROUP, TTF_AMOUNT, TAXABLE_AMOUNT, QTY_UNIT
    FROM NATIXIS_TTF_AUDIT
    WHERE STATUS_REPORT = 1) TA
    JOIN NATIXIS_TTF_GROUP TG ON TG.ID = TA.ID_GROUP
GROUP BY TG.ID, TG.ISIN, TG.DATE_NEG, TG.DATE_VAL, TG.PNA_GROUP, TG.EXONERATION, TA.QTY_UNIT
UNION
SELECT TF.REFCON ID, 'C' || TF.REFCON || ';' || 'S' || ';' || 'N' || ';' || TF.ISIN || ';' || TO_CHAR(TF.DATE_NEG, 'YYYYMMDD') || ';' || TO_CHAR(TF.DATE_VAL, 'YYYYMMDD') || ';' || 
    TF.QT || ';' || TF.QTY_UNIT || ';' || TF.TAXABLE_AMOUNT || ';' || 'Y' || ';' || ' ' || ';' || TF.TTF_AMOUNT || ';' || 'MULT' || ';' || NULL ALL_COLUMN
FROM NATIXIS_TTFCOLLECTED_AUDIT TF
WHERE STATUS_REPORT = 1) T
ORDER BY ID;

spool off;

UPDATE NATIXIS_TTF_AUDIT SET STATUS_REPORT = 2 WHERE STATUS_REPORT = 1;
UPDATE NATIXIS_TTFCOLLECTED_AUDIT SET STATUS_REPORT = 2 WHERE STATUS_REPORT = 1;

/
EXIT;
