SET COLSEP '    '
SET trimout OFF 
SET FEEDBACK OFF
SET heading OFF 
SET verify OFF
SET space 0 
SET NEWPAGE 0 
SET PAGESIZE 0 
SET trimspool ON

SET WRAP OFF
SET TRIMOUT OFF 
SET COLSEP ';'
SET LINESIZE 2000
SET ESCAPE '\'

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ', ';

-- TTF declaration Italian Derivatives --> send to NATIXIS MILAN
spool '&3';

SELECT 173 || ';' || 'D' || ';' ||
    (NVL((SELECT SUM(TTF_AMOUNT) FROM 
        (SELECT ID_GROUP, SUM(TTF_AMOUNT) TTF_AMOUNT FROM
            (SELECT DISTINCT TA.SOUSSECTION, TA.ID_GROUP, TA.TTF_AMOUNT
            FROM NATIXIS_TTF_AUDIT TA
                JOIN NATIXIS_TTF_GROUP TG ON TG.ID = TA.ID_GROUP AND TG.TTF_COUNTRY = 'IT'
            WHERE STATUS_REPORT = 1)
        GROUP BY ID_GROUP)), 0) +
    NVL((SELECT SUM(TTF_AMOUNT) FROM NATIXIS_TTFCOLLECTED_AUDIT WHERE STATUS_REPORT = 1 AND TTF_COUNTRY = 'IT'), 0)) || ';' ||
    (NVL((SELECT COUNT(*) FROM 
        (SELECT ID_GROUP, SUM(TTF_AMOUNT) TTF_AMOUNT FROM
            (SELECT DISTINCT TA.SOUSSECTION, TA.ID_GROUP, TA.TTF_AMOUNT
            FROM NATIXIS_TTF_AUDIT TA
                JOIN NATIXIS_TTF_GROUP TG ON TG.ID = TA.ID_GROUP AND TG.TTF_COUNTRY = 'IT'
            WHERE STATUS_REPORT = 1)
        GROUP BY ID_GROUP)), 0) +
    NVL((SELECT COUNT(*) FROM NATIXIS_TTFCOLLECTED_AUDIT WHERE STATUS_REPORT = 1 AND TTF_COUNTRY = 'IT'), 0)) ||
    ';' || TO_CHAR(to_date('&1', 'YYYYMMDD'), 'YYYYMMDD') || ';' || 
    TO_CHAR(TRUNC(to_date('&1', 'YYYYMMDD'), 'MM'), 'YYYYMM') || ';' || 'NATIXIS_TTFITDRV_' || TO_CHAR(to_date('&1', 'YYYYMMDD'), 'YYYYMMDD') || ';' || 'NATXFRPPMAR' || ';' || 
    'NATIXIS' || ';' || '30 AVENUE PIERRE MENDES-FRANCE - 75013 PARIS' || ';' || 'FRA' || ';' || 'FR73542044524'
FROM DUAL;

SELECT ROWNUM || ';' || T.ALL_COLUMN FROM (
SELECT TD.MVTIDENT || '-' || TD.REFCON || ';' || TD.PRODUCT_FAMILY || ';' || 'N' || ';' || TD.ISIN || ';' || TO_CHAR(TD.DATE_NEG, 'YYYYMMDD')
    || ';' || NULL || ';' || NULL || ';' || NULL || ';' || TD.TAXABLE_AMOUNT || ';' || 'Y' || ';' || ' '
    || ';' || TD.TTF_AMOUNT || ';' || NULL || ';' || NULL ALL_COLUMN
FROM NATIXIS_TTFDERIVATIVES_AUDIT TD
WHERE STATUS_REPORT = 1 AND TTF_COUNTRY = 'IT' AND PRODUCT_FAMILY = &2) T

spool off;

UPDATE NATIXIS_TTFDERIVATIVES_AUDIT SET STATUS_REPORT = 2 WHERE STATUS_REPORT = 1 AND TTF_COUNTRY = 'IT' AND PRODUCT_FAMILY = &2;

/
EXIT;
