DELETE FROM TTF_GROUP_SIMU;

INSERT INTO TTF_GROUP_SIMU (SELECT * FROM NATIXIS_TTF_GROUP);

COMMIT;

DELETE FROM TTF_AUDIT_SIMU;

INSERT INTO TTF_AUDIT_SIMU (SELECT * FROM NATIXIS_TTF_AUDIT);

COMMIT;

DELETE FROM TTFCOLLECTED_AUDIT_SIMU;

INSERT INTO TTFCOLLECTED_AUDIT_SIMU (SELECT * FROM NATIXIS_TTFCOLLECTED_AUDIT);

COMMIT;

DELETE FROM TTFDERIVATIVES_AUDIT_SIMU;

INSERT INTO TTFDERIVATIVES_AUDIT_SIMU (SELECT * FROM NATIXIS_TTFDERIVATIVES_AUDIT);

COMMIT;

DELETE FROM NATIXIS_TTF_GROUP; 

INSERT INTO NATIXIS_TTF_GROUP (SELECT * FROM TTF_GROUP_TEMP);

COMMIT;

DELETE FROM NATIXIS_TTF_AUDIT; 

INSERT INTO NATIXIS_TTF_AUDIT (SELECT * FROM TTF_AUDIT_TEMP);

COMMIT;

DELETE FROM NATIXIS_TTFCOLLECTED_AUDIT;

INSERT INTO NATIXIS_TTFCOLLECTED_AUDIT (SELECT * FROM TTFCOLLECTED_AUDIT_TEMP);

COMMIT;

DELETE FROM NATIXIS_TTFDERIVATIVES_AUDIT; 

INSERT INTO NATIXIS_TTFDERIVATIVES_AUDIT (SELECT * FROM TTFDERIVATIVES_AUDIT_TEMP);

COMMIT;

/
EXIT;
