DELETE FROM TTF_GROUP_TEMP;

INSERT INTO TTF_GROUP_TEMP (SELECT * FROM NATIXIS_TTF_GROUP);

COMMIT;

DELETE FROM TTF_AUDIT_TEMP;

INSERT INTO TTF_AUDIT_TEMP (SELECT * FROM NATIXIS_TTF_AUDIT);

COMMIT;

DELETE FROM TTFCOLLECTED_AUDIT_TEMP;

INSERT INTO TTFCOLLECTED_AUDIT_TEMP (SELECT * FROM NATIXIS_TTFCOLLECTED_AUDIT);

COMMIT;

DELETE FROM TTFDERIVATIVES_AUDIT_TEMP;

INSERT INTO TTFDERIVATIVES_AUDIT_TEMP (SELECT * FROM NATIXIS_TTFDERIVATIVES_AUDIT);

COMMIT;

/
EXIT;
