-- Sequence for unique key, table and trigger before
CREATE SEQUENCE  SEQ_CFG_PRICES  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

-- Price Table
CREATE TABLE CFG_PRICES("ISIN" VARCHAR2(20 BYTE), 
						"ID" NUMBER NOT NULL ENABLE, 
						"DATCRS" DATE NOT NULL ENABLE, 
						"VALCRS" NUMBER NOT NULL ENABLE, 
						"INDCRS" NUMBER, 
						"CUMQUANTI" NUMBER, 
						"CUMVOL" NUMBER, 
						"PLH" NUMBER, 
						"PLB" NUMBER, 
						"OPEN" NUMBER, 
						"HIGH" NUMBER, 
						"CLOSE" NUMBER, 
						"VWAP" NUMBER, 
	 CONSTRAINT "CFG_PRICES_PK" PRIMARY KEY ("ID"));
    
-- Trigger for primary key
CREATE OR REPLACE TRIGGER CFG_PRICES_TRG BEFORE INSERT ON CFG_PRICES FOR EACH ROW
BEGIN
SELECT SEQ_CFG_PRICES.nextval INTO :new.id FROM dual;
END;
/

-- Activate Trigger
ALTER TRIGGER CFG_PRICES_TRG ENABLE;

-- New History columns

-- 'SIZE' IS 1397316165
ALTER TABLE HISTORIQUE ADD (CUMQUANTI NUMBER);
INSERT INTO NEW_HISTORY_COLUMN (TAG, NAME) VALUES (STR_TO_NUM('SIZE'), 'CUMQUANTI');

-- 'CLOS' IS 1129074515
ALTER TABLE HISTORIQUE ADD (CLOSE NUMBER);
INSERT INTO NEW_HISTORY_COLUMN (TAG, NAME) VALUES (STR_TO_NUM('CLOS'), 'CLOSE');

-- 'Vwap' IS 1129074515
ALTER TABLE HISTORIQUE ADD (VWAP NUMBER);
INSERT INTO NEW_HISTORY_COLUMN (TAG, NAME) VALUES (STR_TO_NUM('Vwap'), 'VWAP');

-- FID for RealTime prices
INSERT INTO FIDLIST(ITEM, NAME, SPOT_RT, SPOT_SAVE) VALUES (1, 'LAST', 'LAST', 'LAST');
INSERT INTO FIDLIST(ITEM, NAME, SPOT_RT, SPOT_SAVE) VALUES (2, 'PLH', 'PLH ', 'PLH ');
INSERT INTO FIDLIST(ITEM, NAME, SPOT_RT, SPOT_SAVE) VALUES (3, 'PLB', 'LOW ', 'LOW ');

COMMIT;

BEGIN
	LAST_SPOTS_PKG.INSTALL('HISTORIQUE');  
END;
/