-- Sequence for unique key, table and trigger before
DROP TRIGGER CFG_PRICES_TRG;
DROP SEQUENCE SEQ_CFG_PRICES;
DROP TABLE CFG_PRICES;

ALTER TABLE HISTORIQUE DROP COLUMN CUMQUANTI;
DELETE NEW_HISTORY_COLUMN WHERE NAME = 'CUMQUANTI';

ALTER TABLE HISTORIQUE DROP COLUMN CLOSE;
DELETE NEW_HISTORY_COLUMN WHERE NAME = 'CLOSE';

ALTER TABLE HISTORIQUE DROP COLUMN VWAP;
DELETE NEW_HISTORY_COLUMN WHERE NAME = 'VWAP';

DELETE FIDLIST WHERE ITEM = 1;
DELETE FIDLIST WHERE ITEM = 2;
DELETE FIDLIST WHERE ITEM = 3;

COMMIT;
/








