INSERT INTO TIKEHAU_CONFIG (MODULE,NAME,VALUE,DESCRIPTION,LIST_POSITION)
VALUES ('TKO-SOPHISTOOLKIT-COLONNES','FLOATINGRATE','67883897,67905657,67739540', 'Gets the Interest Rate used for Floating Rate bonds', 0);

INSERT INTO TIKEHAU_CONFIG (MODULE,NAME,VALUE,DESCRIPTION,LIST_POSITION)
VALUES ('TKO-SOPHISTOOLKIT-COLONNES','ALLOTMENT','Internal Securities,Convertibles', 'Check the Allotment group for the instrument', 0);


INSERT INTO TIKEHAU_CONFIG (MODULE,NAME,VALUE,DESCRIPTION,LIST_POSITION)
VALUES ('TKO-SOPHISTOOLKIT-COLONNES-PROVIDER','TKO-CR-DURATION',',PortFolioColumnCallbacker', 'Check the Allotment group for the instrument', 0);


commit ;




