--{{SOPHIS_SQL (do not delete this line)

DROP TABLE TKO_INDICATOR;
DROP SEQUENCE TKO_INDICATOR_SEQ;
DROP TRIGGER TRG_TKO_INDICATOR;
DROP TABLE TKO_INDICATOR_AUDIT;
DROP SEQUENCE TKO_INDICATOR_AUDIT_SEQ;
DROP TABLE TKO_INDICATOR_NAME;

--}}SOPHIS_SQL