CREATE TABLE TKO_INDICATOR_NAME(
    INDICATOR_NAME VARCHAR(50),
    INDICATOR_DISPLAY VARCHAR(100),
    DATA_TYPE CHAR(1) NOT NULL CHECK (DATA_TYPE IN ('D', 'I', 'T')),
    DECIMAL_PRECISION NUMBER(2),
    IS_ENABLED NUMBER(1) NOT NULL CHECK  (IS_ENABLED IN (0, 1)),
    CONSTRAINT TKO_INDICATOR_NAME_PK PRIMARY KEY (INDICATOR_NAME)
);

INSERT INTO TKO_INDICATOR_NAME VALUES('ESG_Score', 'ESG_Score in %', 'D', 0, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('E_Score', 'E_Score in %', 'D', 0, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('S_Score', 'S_Score in %', 'D', 0, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('G_Score', 'G_Score in %', 'D', 0, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('BucketABC', NULL, 'T', NULL, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('DT607', NULL, 'T', NULL, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('DW815', NULL, 'T', NULL, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('DW376', NULL, 'T', NULL, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('DW414', NULL, 'T', NULL, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('F0950', NULL, 'D', 2, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('DS215', NULL, 'T', NULL, 1);
INSERT INTO TKO_INDICATOR_NAME VALUES('RX317', NULL, 'D', 2, 1);

CREATE TABLE TKO_INDICATOR(
    TKO_INDICATOR_ID NUMBER(10),
    INSTRUMENT_ID NUMBER(10),
    INDICATOR_NAME VARCHAR(50),
    DATEVAL DATE,
    VALUE_NUMBER NUMBER,
    VALUE_TEXT VARCHAR(50),
    CONSTRAINT TKO_INDICATOR_PK PRIMARY KEY (TKO_INDICATOR_ID),
    CONSTRAINT TKO_INDICATOR_UNIQUE UNIQUE (INSTRUMENT_ID, INDICATOR_NAME)
);

CREATE SEQUENCE TKO_INDICATOR_SEQ
	START WITH     1000
	INCREMENT BY   1
	NOCACHE
	NOCYCLE;

CREATE TABLE TKO_INDICATOR_AUDIT(
    TKO_INDICATOR_AUDIT_ID NUMBER(10),
    INSTRUMENT_ID NUMBER(10),
    INDICATOR_NAME VARCHAR(50),
    DATEVAL DATE,
    VALUE_NUMBER NUMBER,
    VALUE_TEXT VARCHAR(50),
    CONSTRAINT TKO_INDICATOR_AUDIT_PK PRIMARY KEY (TKO_INDICATOR_AUDIT_ID)
);

CREATE INDEX TKO_INDICATOR_AUDIT_DATEVAL 
ON TKO_INDICATOR_AUDIT(DATEVAL);

CREATE SEQUENCE TKO_INDICATOR_AUDIT_SEQ
	START WITH     1000
	INCREMENT BY   1
	NOCACHE
	NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TKO_INDICATOR
BEFORE INSERT OR UPDATE ON TKO_INDICATOR FOR EACH ROW
BEGIN
    IF (INSERTING OR UPDATING AND :NEW.TKO_INDICATOR_ID IS NOT NULL) THEN
        INSERT INTO TKO_INDICATOR_AUDIT(TKO_INDICATOR_AUDIT_ID, INSTRUMENT_ID, INDICATOR_NAME, DATEVAL, VALUE_NUMBER, VALUE_TEXT)
        VALUES(TKO_INDICATOR_AUDIT_SEQ.NEXTVAL, :NEW.INSTRUMENT_ID, :NEW.INDICATOR_NAME, :NEW.DATEVAL, :NEW.VALUE_NUMBER, :NEW.VALUE_TEXT);
    END IF;
END;
