//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace SophisETL.Extract.SOAExtract.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Extract/SOAExtract")]
    [System.Xml.Serialization.XmlRootAttribute("settings", Namespace="http://www.sophis.net/SophisETL/Extract/SOAExtract", IsNullable=false)]
    public partial class Settings {
        
        private string soaMethodField;
        
        private Params[] soaParametersField;
        
        /// <remarks/>
        public string soaMethod {
            get {
                return this.soaMethodField;
            }
            set {
                this.soaMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("soaParameters")]
        public Params[] soaParameters {
            get {
                return this.soaParametersField;
            }
            set {
                this.soaParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Extract/SOAExtract")]
    public partial class Params {
        
        private string soaParamNameField;
        
        private string soaParamValueField;
        
        /// <remarks/>
        public string soaParamName {
            get {
                return this.soaParamNameField;
            }
            set {
                this.soaParamNameField = value;
            }
        }
        
        /// <remarks/>
        public string soaParamValue {
            get {
                return this.soaParamValueField;
            }
            set {
                this.soaParamValueField = value;
            }
        }
    }
}
