--{{SOPHIS_SQL (do not delete this line)

CREATE TABLE CFGMANAGEMENT_FEES_BY_LEVEL
  (	ID NUMBER(10,0), 
	  CFG_LEVEL NUMBER,
	  RATE NUMBER(16,6),
	  CONSTRAINT CFGMANAGEMENT_FEES_BY_LEVEL_PK PRIMARY KEY (ID,CFG_LEVEL),
	  CONSTRAINT CFGMANAGEMENT_FEES_BY_LEVEL_FK FOREIGN KEY(ID) REFERENCES FUND_FEES_CFGMANAGEMENT(ID) ON DELETE CASCADE
  );
  
insert into CFGMANAGEMENT_FEES_BY_LEVEL (select ID,0,RATE from FUND_FEES_CFGMANAGEMENT);

commit;  
       
--}}SOPHIS_SQL