CREATE OR REPLACE PUBLIC SYNONYM NATIXIS_TTF_GROUP FOR NATIXIS_TTF_GROUP;
GRANT INSERT, SELECT, DELETE ON NATIXIS_TTF_GROUP TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM NATIXIS_TTF_AUDIT FOR NATIXIS_TTF_AUDIT;
GRANT INSERT, SELECT, DELETE ON NATIXIS_TTF_AUDIT TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM NATIXIS_TTFCOLLECTED_AUDIT FOR NATIXIS_TTFCOLLECTED_AUDIT;
GRANT INSERT, SELECT, DELETE ON NATIXIS_TTFCOLLECTED_AUDIT TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM NATIXIS_TTFDERIVATIVES_AUDIT FOR NATIXIS_TTFDERIVATIVES_AUDIT;
GRANT INSERT, SELECT, DELETE ON NATIXIS_TTFDERIVATIVES_AUDIT TO CDCUSER;

CREATE OR REPLACE PUBLIC SYNONYM TTF_GROUP_TEMP FOR TTF_GROUP_TEMP;
GRANT INSERT, SELECT, DELETE ON TTF_GROUP_TEMP TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTF_AUDIT_TEMP FOR TTF_AUDIT_TEMP;
GRANT INSERT, SELECT, DELETE ON TTF_AUDIT_TEMP TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTFCOLLECTED_AUDIT_TEMP FOR TTFCOLLECTED_AUDIT_TEMP;
GRANT INSERT, SELECT, DELETE ON TTFCOLLECTED_AUDIT_TEMP TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTFDERIVATIVES_AUDIT_TEMP FOR TTFDERIVATIVES_AUDIT_TEMP;
GRANT INSERT, SELECT, DELETE ON TTFDERIVATIVES_AUDIT_TEMP TO CDCUSER;

CREATE OR REPLACE PUBLIC SYNONYM TTF_GROUP_SIMU FOR TTF_GROUP_SIMU;
GRANT INSERT, SELECT, DELETE ON TTF_GROUP_SIMU TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTF_AUDIT_SIMU FOR TTF_AUDIT_SIMU;
GRANT INSERT, SELECT, DELETE ON TTF_AUDIT_SIMU TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTFCOLLECTED_AUDIT_SIMU FOR TTFCOLLECTED_AUDIT_SIMU;
GRANT INSERT, SELECT, DELETE ON TTFCOLLECTED_AUDIT_SIMU TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTFDERIVATIVES_AUDIT_SIMU FOR TTFDERIVATIVES_AUDIT_SIMU;
GRANT INSERT, SELECT, DELETE ON TTFDERIVATIVES_AUDIT_SIMU TO CDCUSER;

