CREATE TABLE TTF_GROUP_TEMP
(
  ID              NUMBER,
  ISIN            VARCHAR2(50 BYTE),
  PRODUCT_FAMILY  NUMBER(2),
  DATE_NEG        DATE,
  DATE_VAL        DATE,
  EXONERATION     NUMBER(2),
  PNA_GROUP       NUMBER(20,2),
  TTF_COUNTRY     VARCHAR2(2 BYTE),
  PNA_AVG_PRICE   NUMBER(20,8),
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE TTF_AUDIT_TEMP
(
  REFCON          NUMBER(10),
  ID_GROUP        NUMBER(10),
  QTY_UNIT        VARCHAR2(3 BYTE),
  ID_TTF_SOPHIS   NUMBER(10),
  DATE_CALCUL     DATE,
  SOUSSECTION     VARCHAR2(10 BYTE),
  PNA_AVG_PRICE   NUMBER(20,8),
  PNA_SECTION     NUMBER(20,2),
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE),
  STATUS_IMPORT   NUMBER(1),
  STATUS_REPORT   NUMBER(1),
  TTF_RATE        NUMBER(20,4)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE TTFCOLLECTED_AUDIT_TEMP
(
  REFCON          NUMBER(10),
  QTY_UNIT        VARCHAR2(3 BYTE),
  ID_TTF_SOPHIS   NUMBER(10),
  DATE_CALCUL     DATE,
  FOLIO           NUMBER(10),
  SECTION         VARCHAR2(40 BYTE),
  QT              NUMBER(20,2),
  PRICE           NUMBER(20,8),
  ISIN            VARCHAR2(50 BYTE),
  DATE_NEG        DATE,
  DATE_VAL        DATE,
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE),
  STATUS_IMPORT   NUMBER(1),
  STATUS_REPORT   NUMBER(1),
  TTF_COUNTRY     VARCHAR2(2 BYTE)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE TTFDERIVATIVES_AUDIT_TEMP
(
  REFCON          NUMBER(10),
  MVTIDENT        NUMBER(10),
  DATE_CALCUL     DATE,
  FOLIO           NUMBER(10),
  SECTION         VARCHAR2(40 BYTE),
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE),
  STATUS_REPORT   NUMBER(1),
  ISIN            VARCHAR2(50 BYTE),
  PRODUCT_FAMILY  NUMBER(2),
  DATE_NEG        DATE,
  TTF_COUNTRY     VARCHAR2(2 BYTE)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TTF_GROUP_SIMU
(
  ID              NUMBER,
  ISIN            VARCHAR2(50 BYTE),
  PRODUCT_FAMILY  NUMBER(2),
  DATE_NEG        DATE,
  DATE_VAL        DATE,
  EXONERATION     NUMBER(2),
  PNA_GROUP       NUMBER(20,2),
  TTF_COUNTRY     VARCHAR2(2 BYTE),
  PNA_AVG_PRICE   NUMBER(20,8),
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE TTF_AUDIT_SIMU
(
  REFCON          NUMBER(10),
  ID_GROUP        NUMBER(10),
  QTY_UNIT        VARCHAR2(3 BYTE),
  ID_TTF_SOPHIS   NUMBER(10),
  DATE_CALCUL     DATE,
  SOUSSECTION     VARCHAR2(10 BYTE),
  PNA_AVG_PRICE   NUMBER(20,8),
  PNA_SECTION     NUMBER(20,2),
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE),
  STATUS_IMPORT   NUMBER(1),
  STATUS_REPORT   NUMBER(1),
  TTF_RATE        NUMBER(20,4)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE TTFCOLLECTED_AUDIT_SIMU
(
  REFCON          NUMBER(10),
  QTY_UNIT        VARCHAR2(3 BYTE),
  ID_TTF_SOPHIS   NUMBER(10),
  DATE_CALCUL     DATE,
  FOLIO           NUMBER(10),
  SECTION         VARCHAR2(40 BYTE),
  QT              NUMBER(20,2),
  PRICE           NUMBER(20,8),
  ISIN            VARCHAR2(50 BYTE),
  DATE_NEG        DATE,
  DATE_VAL        DATE,
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE),
  STATUS_IMPORT   NUMBER(1),
  STATUS_REPORT   NUMBER(1),
  TTF_COUNTRY     VARCHAR2(2 BYTE)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE TTFDERIVATIVES_AUDIT_SIMU
(
  REFCON          NUMBER(10),
  MVTIDENT        NUMBER(10),
  DATE_CALCUL     DATE,
  FOLIO           NUMBER(10),
  SECTION         VARCHAR2(40 BYTE),
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE),
  STATUS_REPORT   NUMBER(1),
  ISIN            VARCHAR2(50 BYTE),
  PRODUCT_FAMILY  NUMBER(2),
  DATE_NEG        DATE,
  TTF_COUNTRY     VARCHAR2(2 BYTE)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM TTF_GROUP_TEMP FOR TTF_GROUP_TEMP;
GRANT INSERT, SELECT, DELETE ON TTF_GROUP_TEMP TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTF_AUDIT_TEMP FOR TTF_AUDIT_TEMP;
GRANT INSERT, SELECT, DELETE ON TTF_AUDIT_TEMP TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTFCOLLECTED_AUDIT_TEMP FOR TTFCOLLECTED_AUDIT_TEMP;
GRANT INSERT, SELECT, DELETE ON TTFCOLLECTED_AUDIT_TEMP TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTFDERIVATIVES_AUDIT_TEMP FOR TTFDERIVATIVES_AUDIT_TEMP;
GRANT INSERT, SELECT, DELETE ON TTFDERIVATIVES_AUDIT_TEMP TO CDCUSER;

CREATE OR REPLACE PUBLIC SYNONYM TTF_GROUP_SIMU FOR TTF_GROUP_SIMU;
GRANT INSERT, SELECT, DELETE ON TTF_GROUP_SIMU TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTF_AUDIT_SIMU FOR TTF_AUDIT_SIMU;
GRANT INSERT, SELECT, DELETE ON TTF_AUDIT_SIMU TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTFCOLLECTED_AUDIT_SIMU FOR TTFCOLLECTED_AUDIT_SIMU;
GRANT INSERT, SELECT, DELETE ON TTFCOLLECTED_AUDIT_SIMU TO CDCUSER;
CREATE OR REPLACE PUBLIC SYNONYM TTFDERIVATIVES_AUDIT_SIMU FOR TTFDERIVATIVES_AUDIT_SIMU;
GRANT INSERT, SELECT, DELETE ON TTFDERIVATIVES_AUDIT_SIMU TO CDCUSER;

