--------NATIXIS_TTF_GROUP
CREATE TABLE NATIXIS_TTF_GROUP
(
  ID              NUMBER,
  ISIN            VARCHAR2(50 BYTE),
  PRODUCT_FAMILY  NUMBER(2),
  DATE_NEG        DATE,
  DATE_VAL        DATE,
  EXONERATION     NUMBER(2),
  PNA_GROUP       NUMBER(20,2),
  TTF_COUNTRY     VARCHAR2(2 BYTE),
  PNA_AVG_PRICE   NUMBER(20,8),
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX IDX_NATIXIS_TTF_GROUP ON NATIXIS_TTF_GROUP
(ISIN, PRODUCT_FAMILY, DATE_NEG, DATE_VAL, EXONERATION)
LOGGING
TABLESPACE CDC_IDX_10M
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX PK_NATIXIS_TTF_GROUP ON NATIXIS_TTF_GROUP
(ID)
LOGGING
TABLESPACE CDC_DAT_10M
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             10M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

-----------NATIXIS_TTF_AUDIT
CREATE TABLE NATIXIS_TTF_AUDIT
(
  REFCON          NUMBER(10),
  ID_GROUP        NUMBER(10),
  QTY_UNIT        VARCHAR2(3 BYTE),
  ID_TTF_SOPHIS   NUMBER(10),
  DATE_CALCUL     DATE,
  SOUSSECTION     VARCHAR2(10 BYTE),
  PNA_AVG_PRICE   NUMBER(20,8),
  PNA_SECTION     NUMBER(20,2),
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE),
  STATUS_IMPORT   NUMBER(1),
  STATUS_REPORT   NUMBER(1),
  TTF_RATE        NUMBER(20,4)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX IDX_NATIXIS_TTF_AUDIT_DATE_SS ON NATIXIS_TTF_AUDIT
(DATE_CALCUL, SOUSSECTION)
LOGGING
TABLESPACE CDC_IDX_10M
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX IDX_NATIXIS_TTF_AUDIT_GROUP ON NATIXIS_TTF_AUDIT
(ID_GROUP)
LOGGING
TABLESPACE CDC_IDX_10M
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX PK_NATIXIS_TTF_AUDIT ON NATIXIS_TTF_AUDIT
(REFCON)
LOGGING
TABLESPACE CDC_DAT_10M
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             10M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

-----------NATIXIS_TTFCOLLECTED_AUDIT
CREATE TABLE NATIXIS_TTFCOLLECTED_AUDIT
(
  REFCON          NUMBER(10),
  QTY_UNIT        VARCHAR2(3 BYTE),
  ID_TTF_SOPHIS   NUMBER(10),
  DATE_CALCUL     DATE,
  FOLIO           NUMBER(10),
  SECTION         VARCHAR2(40 BYTE),
  QT              NUMBER(20,2),
  PRICE           NUMBER(20,8),
  ISIN            VARCHAR2(50 BYTE),
  DATE_NEG        DATE,
  DATE_VAL        DATE,
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE),
  STATUS_IMPORT   NUMBER(1),
  STATUS_REPORT   NUMBER(1),
  TTF_COUNTRY     VARCHAR2(2 BYTE)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PK_NATIXIS_TTFCOLLECTED_AUDIT ON NATIXIS_TTFCOLLECTED_AUDIT
(REFCON)
LOGGING
TABLESPACE CDC_DAT_10M
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             10M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

------------NATIXIS_TTFDERIVATIVES_AUDIT
CREATE TABLE NATIXIS_TTFDERIVATIVES_AUDIT
(
  REFCON          NUMBER(10),
  MVTIDENT        NUMBER(10),
  DATE_CALCUL     DATE,
  FOLIO           NUMBER(10),
  SECTION         VARCHAR2(40 BYTE),
  TAXABLE_AMOUNT  NUMBER(20,2),
  TTF_AMOUNT      NUMBER(20,2),
  TTF_CUR         VARCHAR2(3 BYTE),
  STATUS_REPORT   NUMBER(1),
  ISIN            VARCHAR2(50 BYTE),
  PRODUCT_FAMILY  NUMBER(2),
  DATE_NEG        DATE,
  TTF_COUNTRY     VARCHAR2(2 BYTE)
)
TABLESPACE CDC_DAT_10M
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PK_NATIXIS_TTFDERIVATIVES ON NATIXIS_TTFDERIVATIVES_AUDIT
(REFCON)
LOGGING
TABLESPACE CDC_DAT_10M
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             10M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
