//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolkitReporting.NET {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolkitReporting.NET.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel template files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string ExcelTemplateFilter {
            get {
                return ResourceManager.GetString("ExcelTemplateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an excel template file.
        /// </summary>
        internal static string ExcelTemplateTitle {
            get {
                return ResourceManager.GetString("ExcelTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel template file is not defined for the report..
        /// </summary>
        internal static string ExExcelTemplateNotDefined {
            get {
                return ResourceManager.GetString("ExExcelTemplateNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file is not defined..
        /// </summary>
        internal static string ExOutputFileNotDefined {
            get {
                return ResourceManager.GetString("ExOutputFileNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report has been generated successfully..
        /// </summary>
        internal static string FileGenerated {
            get {
                return ResourceManager.GetString("FileGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report has not been generated for some reason. Please see the log file for more details..
        /// </summary>
        internal static string FileNotGenerated {
            get {
                return ResourceManager.GetString("FileNotGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The xslt file has been generated successfully..
        /// </summary>
        internal static string FileXsltGenerated {
            get {
                return ResourceManager.GetString("FileXsltGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The xslt file has not been generated for some reason. Please see the log file for more details..
        /// </summary>
        internal static string FileXsltNotGenerated {
            get {
                return ResourceManager.GetString("FileXsltNotGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation files (*.xslt)|*.xslt|All Files (*.*)|*.*.
        /// </summary>
        internal static string GenerateXsltFilter {
            get {
                return ResourceManager.GetString("GenerateXsltFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save xslt file as.
        /// </summary>
        internal static string GenerateXsltTitle {
            get {
                return ResourceManager.GetString("GenerateXsltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters source exists already. Do you want to regenerate it ?.
        /// </summary>
        internal static string MsgParameterSourceOverwriteConfirm {
            get {
                return ResourceManager.GetString("MsgParameterSourceOverwriteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your current changes?.
        /// </summary>
        internal static string MsgSaveChangesQuestion {
            get {
                return ResourceManager.GetString("MsgSaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a tag, a source and enter a column name.
        /// </summary>
        internal static string MsgSelectParamColumnManual {
            get {
                return ResourceManager.GetString("MsgSelectParamColumnManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a tag and a column to make a mapping.
        /// </summary>
        internal static string MsgSelectParamColumns {
            get {
                return ResourceManager.GetString("MsgSelectParamColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the excel template file.
        /// </summary>
        internal static string PropertyExcelTemplateDesc {
            get {
                return ResourceManager.GetString("PropertyExcelTemplateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Template.
        /// </summary>
        internal static string PropertyExcelTemplateDisp {
            get {
                return ResourceManager.GetString("PropertyExcelTemplateDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the excel/pdf output file.
        /// </summary>
        internal static string PropertyOutputFileDesc {
            get {
                return ResourceManager.GetString("PropertyOutputFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel/PDF output file.
        /// </summary>
        internal static string PropertyOutputFileDisp {
            get {
                return ResourceManager.GetString("PropertyOutputFileDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map between excel tags and portfolio columns.
        /// </summary>
        internal static string PropertyParamColMapDesc {
            get {
                return ResourceManager.GetString("PropertyParamColMapDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Column Map.
        /// </summary>
        internal static string PropertyParamColMapDisp {
            get {
                return ResourceManager.GetString("PropertyParamColMapDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLQuery.
        /// </summary>
        internal static string PropertyQueryDesc {
            get {
                return ResourceManager.GetString("PropertyQueryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string PropertyQueryDisp {
            get {
                return ResourceManager.GetString("PropertyQueryDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show column header.
        /// </summary>
        internal static string PropertyShowHeaderDesc {
            get {
                return ResourceManager.GetString("PropertyShowHeaderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Header.
        /// </summary>
        internal static string PropertyShowHeaderDisp {
            get {
                return ResourceManager.GetString("PropertyShowHeaderDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag where to fill the data in.
        /// </summary>
        internal static string PropertyTableTagDesc {
            get {
                return ResourceManager.GetString("PropertyTableTagDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Tag.
        /// </summary>
        internal static string PropertyTableTagDisp {
            get {
                return ResourceManager.GetString("PropertyTableTagDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet of the selected excel template file.
        /// </summary>
        internal static string PropertyWorksheetDesc {
            get {
                return ResourceManager.GetString("PropertyWorksheetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet.
        /// </summary>
        internal static string PropertyWorksheetDisp {
            get {
                return ResourceManager.GetString("PropertyWorksheetDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the xml output file.
        /// </summary>
        internal static string PropertyXmlOutputFileDesc {
            get {
                return ResourceManager.GetString("PropertyXmlOutputFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml output file.
        /// </summary>
        internal static string PropertyXmlOutputFileDisp {
            get {
                return ResourceManager.GetString("PropertyXmlOutputFileDisp", resourceCulture);
            }
        }
    }
}
