--{{SOPHIS_SQL (do not delete this line)

--ALTER TABLE INFO_SUP ADD VALUE_DATE NUMBER; -NOT USED ANYMORE

ALTER TABLE TITRES ADD CFG_RISK_SPREAD NUMBER;
ALTER TABLE TITRES_HISTO ADD CFG_RISK_SPREAD NUMBER;

CREATE TABLE CFG_YC_INFOS
(
   IDENT NUMBER(10,0) NOT NULL ENABLE, 
   COURBE NUMBER(38,0) NOT NULL ENABLE, 
   MATURITY_DATE  NUMBER NOT NULL ENABLE, 
   RATE NUMBER, --y
   VALUE_DATE NUMBER,
   CONSTRAINT "PK_CFG_YC_INFOS" PRIMARY KEY ("IDENT")
)

CREATE OR REPLACE TRIGGER CFG_YC_POINTS_TRIGGER 
AFTER DELETE OR INSERT ON GR_POINTS
FOR EACH ROW
BEGIN

if inserting then
		begin
		insert into CFG_YC_INFOS (IDENT,COURBE,MATURITY_DATE,RATE)
		values (:new.IDENT, :new.COURBE, :new.X, :new.Y);
		end;
elsif deleting then
		begin
    delete from CFG_YC_INFOS
     where IDENT= :old.IDENT;
    end;
    end if;
END;


commit;

--}}SOPHIS_SQL