//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace SophisETL.Transform.PercentOfSum.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/PercentOfSum")]
    [System.Xml.Serialization.XmlRootAttribute("settings", Namespace="http://www.sophis.net/SophisETL/Transform/PercentOfSum", IsNullable=false)]
    public partial class Settings {
        
        private PercentOfSum percentOfSumField;
        
        /// <remarks/>
        public PercentOfSum percentOfSum {
            get {
                return this.percentOfSumField;
            }
            set {
                this.percentOfSumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/PercentOfSum")]
    public partial class PercentOfSum {
        
        private bool recordListField;
        
        private string fieldAverageField;
        
        private string fieldTargetField;
        
        private string fieldListField;
        
        /// <remarks/>
        public bool recordList {
            get {
                return this.recordListField;
            }
            set {
                this.recordListField = value;
            }
        }
        
        /// <remarks/>
        public string fieldAverage {
            get {
                return this.fieldAverageField;
            }
            set {
                this.fieldAverageField = value;
            }
        }
        
        /// <remarks/>
        public string fieldTarget {
            get {
                return this.fieldTargetField;
            }
            set {
                this.fieldTargetField = value;
            }
        }
        
        /// <remarks/>
        public string fieldList {
            get {
                return this.fieldListField;
            }
            set {
                this.fieldListField = value;
            }
        }
    }
}
