//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace SophisETL.Transform.TickerToReplaceISIN.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/TickerToReplaceISIN")]
    [System.Xml.Serialization.XmlRootAttribute("settings", Namespace="http://www.sophis.net/SophisETL/Transform/TickerToReplaceISIN", IsNullable=false)]
    public partial class Settings {
        
        private Replace[] replaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("replace")]
        public Replace[] replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/TickerToReplaceISIN")]
    public partial class Replace {
        
        private string iSINFieldField;
        
        private string tICKERFieldField;
        
        private string referenceMatchField;
        
        private string referenceNameField;
        
        /// <remarks/>
        public string ISINField {
            get {
                return this.iSINFieldField;
            }
            set {
                this.iSINFieldField = value;
            }
        }
        
        /// <remarks/>
        public string TICKERField {
            get {
                return this.tICKERFieldField;
            }
            set {
                this.tICKERFieldField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceMatch {
            get {
                return this.referenceMatchField;
            }
            set {
                this.referenceMatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string referenceName {
            get {
                return this.referenceNameField;
            }
            set {
                this.referenceNameField = value;
            }
        }
    }
}
