//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace SophisETL.Transform.Replace.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/Replace")]
    [System.Xml.Serialization.XmlRootAttribute("settings", Namespace="http://www.sophis.net/SophisETL/Transform/Replace", IsNullable=false)]
    public partial class Settings {
        
        private Replace[] replaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("replace")]
        public Replace[] replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/Replace")]
    public partial class Replace {
        
        private SimpleMatch[] simpleMatchField;
        
        private RegexMatch[] regexMatchField;
        
        private string sourceFieldField;
        
        private string targetFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("simpleMatch")]
        public SimpleMatch[] simpleMatch {
            get {
                return this.simpleMatchField;
            }
            set {
                this.simpleMatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regexMatch")]
        public RegexMatch[] regexMatch {
            get {
                return this.regexMatchField;
            }
            set {
                this.regexMatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceField {
            get {
                return this.sourceFieldField;
            }
            set {
                this.sourceFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string targetField {
            get {
                return this.targetFieldField;
            }
            set {
                this.targetFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/Replace")]
    public partial class SimpleMatch {
        
        private string matchField;
        
        private string replaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string match {
            get {
                return this.matchField;
            }
            set {
                this.matchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/Replace")]
    public partial class RegexMatch {
        
        private string matchField;
        
        private string replaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string match {
            get {
                return this.matchField;
            }
            set {
                this.matchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
            }
        }
    }
}
