CREATE TABLE GL_INTERFACE_AUDIT
   (	ID NUMBER NOT NULL ENABLE, 
	LEDGER VARCHAR2(50 BYTE), 
	CATEGORY VARCHAR2(50 BYTE), 
	SOURCE VARCHAR2(50 BYTE), 
	CURRENCY VARCHAR2(10 BYTE), 
	ACCOUNTING_DATE DATE, 
	COMPANY VARCHAR2(50 BYTE), 
	CURRENTCY VARCHAR2(50 BYTE), 
	ACCOUNT VARCHAR2(80 BYTE), 
	SUBACCOUNT VARCHAR2(80 BYTE), 
	REGION VARCHAR2(20 BYTE), 
	RELATION VARCHAR2(20 BYTE), 
	FUTURE VARCHAR2(20 BYTE), 
	DEBIT NUMBER, 
	CREDIT NUMBER, 
	LINE_DESCRIPTION VARCHAR2(100 BYTE), 
	JOURNAL_NAME VARCHAR2(50 BYTE), 
	JOURNAL_DESCRIPTION VARCHAR2(100 BYTE), 
	TREATMENT_TIME TIMESTAMP (6), 
	OPERATOR_ID NUMBER, 
	STATUS_AUDIT NUMBER, 
	ID_POSTING NUMBER
	);
CREATE UNIQUE INDEX IDX_GL_INTERFACE_AUDIT ON GL_INTERFACE_AUDIT(ID);

-- Create Sequence

CREATE SEQUENCE  KAMCO_GL_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 31 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;



	
	