//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8806
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace SophisETL.Transform.GroupByAndSum.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/GroupByAndSum")]
    [System.Xml.Serialization.XmlRootAttribute("settings", Namespace="http://www.sophis.net/SophisETL/Transform/GroupByAndSum", IsNullable=false)]
    public partial class Settings {
        
        private GroupByElement[] groupByListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupByList")]
        public GroupByElement[] groupByList {
            get {
                return this.groupByListField;
            }
            set {
                this.groupByListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/GroupByAndSum")]
    public partial class GroupByElement {
        
        private string groupByFieldField;
        
        private string sumFieldField;

        private string filterFieldField;

        private string folioPathFieldField;

        private string depositaryFieldField;

        /// <remarks/>
        public string groupByField {
            get {
                return this.groupByFieldField;
            }
            set {
                this.groupByFieldField = value;
            }
        }
        
        /// <remarks/>
        public string sumField {
            get {
                return this.sumFieldField;
            }
            set {
                this.sumFieldField = value;
            }
        }

        /// <summary>
        ///  <remarks/>
        /// </summary>
        public string filterField
        {
            get
            {
                return this.filterFieldField;
            }
            set
            {
                this.filterFieldField = value;
            }
        }
        /// <summary>
        ///  <remarks/>
        /// </summary>
        public string folioPathField
        {
            get
            {
                return this.folioPathFieldField;
            }
            set
            {
                this.folioPathFieldField = value;
            }
        }

        public string depositaryField
        {
            get
            {
                return this.depositaryFieldField;
            }
            set
            {
                this.depositaryFieldField = value;
            }
        }
    }
}
