--{{SOPHIS_SQL (do not delete this line)

WHENEVER SQLERROR CONTINUE
INSERT INTO BO_TREASURY_EXT_REF_DEF (REF_ID,REF_NAME) SELECT 2,'DelegateManagerID' FROM DUAL WHERE NOT EXISTS (SELECT * FROM BO_TREASURY_EXT_REF_DEF WHERE REF_ID = 2);
INSERT INTO BO_TREASURY_EXT_REF_DEF (REF_ID,REF_NAME) SELECT 3,'RootPortfolio' FROM DUAL WHERE NOT EXISTS (SELECT * FROM BO_TREASURY_EXT_REF_DEF WHERE REF_ID = 3);
INSERT INTO BO_TREASURY_EXT_REF_DEF (REF_ID,REF_NAME) SELECT 4,'AlternativeCashFolioID' FROM DUAL WHERE NOT EXISTS (SELECT * FROM BO_TREASURY_EXT_REF_DEF WHERE REF_ID = 4);

begin
    tk_add_histomvts_column('TKT_RBC_TRADE_ID', 'VARCHAR2(256)', NULL, 'RBC Transaction ID');
end;

commit;

-- 

create TABLE MEDIO_FXALL_TEMP_EXTRNREF (PLACEMENT_ID NUMBER,ENTITY NUMBER,EXTERNAL_REFERENCE VARCHAR2(250));

commit;

--}}SOPHIS_SQL
