#pragma once

#define CATEGORY_NAME_LENGTH 40

//Tag Elementss
# define TAG_CATEGORY										"Hedging Flag"
# define TAG_ELEMENT_HEDGED_POSITION						"Hedged Position"

// Allotment
#define ALLOTMENT_CDX										"CDX"
#define ALLOTMENT_CDS										"CDS"
#define ALLOTMENT_TRS										"TRS"
#define ALLOTMENT_CB								    	"CONVERTIBLE BOND"
#define ALLOTMENT_COCO										"COCO BOND"
#define ALLOTMENT_BARRIER_OPTION							"OTC OPTION BARRIER"
#define ALLOTMENT_CCY_FUTURE								"CCY FUTURE"
#define ALLOTMENT_CERTIFICATE								"CERTIFICATE"
#define ALLOTMENT_IR_DERIVATIVE								"IR DERIVATIVE"
#define ALLOTMENT_NDF										"NDF"
#define ALLOTMENT_OTC_FX_OPTION_SINGLE						"OTC FX OPTION SINGLE"
#define ALLOTMENT_TRS_EQUITY_SINGLE							"TRS EQUITY SINGLE"
#define ALLOTMENT_TRS_EQUITY_BASKET							"TRS EQUITY BASKET"
#define ALLOTMENT_TRS_FIXED_INCOME_SINGLE					"TRS FIXED INCOME SINGLE"
#define ALLOTMENT_FX_FORWARD								"FX FORWARD"
#define ALLOTMENT_LISTED_OPTION								"LISTED OPTION"

// Toolkit columns 
#define MEDIO_COLUMNGROP_TKT								"Toolkit"
#define MEDIO_COLUMN_TKT_NETCOMMITMENT						"Net Commitment"
#define MEDIO_COLUMN_TKT_HEDGINGPOSITION					"Hedging Status"
#define MEDIO_COLUMN_TKT_AIFMDEXPOSURE						"AIFMD Exposure (Gross)"
#define MEDIO_COLUMN_TKT_AIFMDLEVERAGE						"AIFMD Levergae (Gross)"
#define MEDIO_COLUMN_TKT_FUNDGROSSCOMMITMENT				"Fund Gross Commitment"
#define MEDIO_COLUMN_TKT_AIFMDLEVERAGE_COMMITMENT			"AIFMD Exposure (Commitment)"
#define MEDIO_COLUMN_TKT_AIFMDLEVERAGET_COMMITMENT			"AIFMD Levergae (Commitment)"

// Standard columns 
#define MEDIO_COLUMN_STD_UCITSCOMMITMENT					"UCITS Commitment"
#define MEDIO_COLUMN_STD_MARKETVALUE						"Market Value"
#define MEDIO_COLUMN_STD_InstrumentType						"Instrument type"



// GUI field names == table column names
#define MEDIO_GUI_FIELDNAME_MAX_DELTA						"MAX_DELTA"
#define MEDIO_GUI_FIELDNAME_HEDGE_CHECK						"MEDIO_HEDGE_CHECK"
#define MEDIO_GUI_FIELDNAME_HEDGE_COMMENT					"MEDIO_COMMENTS"
#define MEDIO_GUI_FIELDNAME_OUTSIDE_HRS						"MEDIO_OUTSIDE_HRS"
#define MEDIO_GUI_FIELDNAME_MARKET_TIMEZONE					"MEDIO_MARKET_TIMEZONE"
#define MEDIO_GUI_FIELDNAME_PIT_CLOSING_TIME				"MEDIO_PIT_CLOSING"
#define MEDIO_GUI_FIELDNAME_PIT_OPENING_TIME				"MEDIO_PIT_OPENING"
#define MEDIO_GUI_FIELDNAME_OUTSIDE_HRS_LOG					"MEDIO_OUTSIDE_HRS_LOG"
#define MEDIO_GUI_FIELDNAME_PARENT_ORDER_ID					"MEDIO_PARENTORDERID"
#define MEDIO_GUI_FIELDNAME_RBC_TRADE_ID					"TKT_RBC_TRADE_ID"
#define MEDIO_GUI_FIELDNAME_SWAP_VEGA_NOTIONAL				"MEDIO_VEGA_NOTIONAL"
#define MEDIO_GUI_FIELDNAME_SWAP_VOL_STRIKE					"MEDIO_VOL_STRIKE"
#define MEDIO_GUI_FIELDNAME_SWAP_VAR_DAYS					"MEDIO_VARIANCE_DAYS"
#define MEDIO_GUI_FIELDNAME_RBC_COMMENT						"TKT_RBC_COMMENT"
#define MEDIO_GUI_FIELDNAME_RBC_CAPSREF						"TKT_RBC_CAPS_REF"
#define MEDIO_GUI_FIELDNAME_RBC_UCITSVCODE					"TKT_RBC_UCITSVCODE"
#define MEDIO_GUI_FIELDNAME_RBC_TRANSTYPE					"TKT_RBC_TRANSTYPE"

// User rights 
#define MEDIO_USERRIGHT_HEDGECHECK							"Hedge Check"

// Third party user property 
#define MEDIO_THIRDPARTY_PROP_CREDIT						"MEDIO_Credit"
#define MEDIO_THIRDPARTY_PROP_RATING						"MEDIO_Rating"

// Trade External Ref
#define MEDIO_TRADE_EXTREF_RBC_REPORTING_BE					"RBC_REPORTING_BE"
#define MEDIO_TRADE_EXTREF_RBC_REPORTING_BE_EXCEPTION		"RBC_REPORTING_BE_EXCEPTION"


/// Config 
// --- Section ---
#define MEDIO_BO_DEALCHECK_CUSTOM_SECTION					"MEDIO_BACKOFFICE_DEALCHECK"
#define MEDIO_BO_DEALACTION_CUSTOM_SECTION					"MEDIO_BACKOFFICE_DEALACTION"
#define MEDIO_BO_ALLOTMENT_CUSTOM_SECTION					"MEDIO_ALLOTMENT"


// --- Entry ---
#define MEDIO_BO_DEALCHECK_CUSTOM_SECTION_SHORTSELLBUSGROUP						"ShortSellBusEventGroup"
#define MEDIO_BO_DEALCHECK_CUSTOM_SECTION_MODIFYEVENTID							"ModifyEventID"
#define MEDIO_BO_DEALCHECK_CUSTOM_SECTION_SHORTSELLBUSEVNT						"ShortSellBusEvent"
#define MEDIO_BO_DEALACTION_CUSTOM_SECTION_TRADETHRUZEROKERNELGROUP				"TradeThruZeroKernelStatusGroup"
#define MEDIO_BO_DEALCHECK_CUSTOM_SECTION_BENAME								"RBC_REPORTING_BE Name"
#define MEDIO_BO_DEALCHECK_CUSTOM_SECTION_BEEXCEPTIONNAME						"RBC_REPORTING_BE_EXCEPTION Name"
#define MEDIO_BO_DEALCHECK_CUSTOM_SECTION_AFTERFINALEXECEVENTNAME				"AfterFinalExecution_EventName"
#define MEDIO_BO_ALLOTMEN_CUSTOM_SECTION_CDX									"CDX"


namespace MEDIOEnums 
{
	enum eHedgeStatus : int
	{
		NoStatus    = -1,
		NotHedging  = 0,
		Hedging     = 1,
		Validated   = 2,
		Refused     = 3
	};

	enum eActionType : int
	{
		NoAction = -1,
		Save = 0,
		Validate = 1,
		Refuse = 2,
		Create = 3,
		Modify = 4
	};

}


