
WHENEVER SQLERROR CONTINUE

begin
    tk_add_histomvts_column('TKT_RBC_TRADE_ID', 'VARCHAR2(256)', NULL, 'RBC Transaction ID');
end;

INSERT INTO SWAP_POS_REFS_DEF (REF_NAME,REDUNDANT,USE_CUSTOM_REF) SELECT 'RBC_TRADE_ID',1,1 FROM DUAL WHERE NOT EXISTS (SELECT * FROM SWAP_POS_REFS_DEF WHERE REF_NAME = 'RBC_TRADE_ID');

commit;