--{{SOPHIS_SQL (do not delete this line)

CREATE TABLE EMC_DEFINITION_COLUMN
(
    ID_COLUMN NUMBER(5),
    NAME_COLUMN VARCHAR2(100),
    DEFINITION VARCHAR2(4000)
);
CREATE UNIQUE INDEX PK_EMC_DEFINITION_COLUMN_NAME ON EMC_DEFINITION_COLUMN(NAME_COLUMN);

--}}SOPHIS_SQL