#ifndef _MEDIO_UCITS_CALCULATION_Version_H_
#define _MEDIO_UCITS_CALCULATION_Version_H_

#include "SphInc\Value\kernel\SphBuildVersion.h"
#include "..\..\MediolanumVersion.h"

#define MEDIO_UCITS_CALCULATION_VERSION 				MEDIOLANUM_VERSION
#define MEDIO_UCITS_CALCULATION_VERSION_STR				MEDIOLANUM_VERSION_STR
#ifdef WIN32
	#define MEDIO_UCITS_CALCULATION_TOOLKIT_DESCRIPTION	"MEDIO_UCITS_CALCULATION (x86)"
#else
	#define MEDIO_UCITS_CALCULATION_TOOLKIT_DESCRIPTION	"MEDIO_UCITS_CALCULATION (x64)"
#endif

#endif // _MEDIO_UCITS_CALCULATION_Version_H_
