--{{SOPHIS_SQL (do not delete this line)

create table CFG_RETRO_FEES_PARAMETERS
(
  BUSINESS_PARTNER_ID   NUMBER(10,0),
  BUSINESS_PARTNER_TYPE NUMBER(2,0),
  FUND_ID               NUMBER(10,0),
  COMPUTATION_METHOD    NUMBER(2,0),
  START_DATE            DATE,
  END_DATE              DATE,
  COMMISSION_RATE       NUMBER,
  LEVEL_1               NUMBER,
  RETROCESSION_RATE_1   NUMBER,
  LEVEL_2               NUMBER,
  RETROCESSION_RATE_2   NUMBER,
  LEVEL_3               NUMBER,
  RETROCESSION_RATE_3   NUMBER,
  LEVEL_4               NUMBER, 
  RETROCESSION_RATE_4   NUMBER,
  TVA_RATE              NUMBER  
);

create table CFG_RETRO_FEES_RESULTS
(
  FUND_ID               NUMBER(10,0),
  BUSINESS_PARTNER_ID   NUMBER(10,0),
  BUSINESS_PARTNER_TYPE NUMBER(2,0),
  COMPUTATION_METHOD    NUMBER(2,0),  
  START_DATE            DATE,
  END_DATE              DATE,  
  AVERAGE_ASSET         NUMBER, 
  NB_DAYS               NUMBER(10,0), 
  RETRO_RATE            NUMBER, 
  COMMISSION_RATE       NUMBER,
  AMOUNT_HT             NUMBER,
  AMOUNT_TTC            NUMBER,
  CONSTRAINT PK_FG_RETRO_FEES_RESULTS PRIMARY KEY (FUND_ID,BUSINESS_PARTNER_ID,BUSINESS_PARTNER_TYPE,COMPUTATION_METHOD,START_DATE,END_DATE)
);

create table CFG_RETRO_FEES_DETAILS
(
  FUND_ID                     NUMBER(10,0),
  BUSINESS_PARTNER_ID         NUMBER(10,0),
  BUSINESS_PARTNER_TYPE       NUMBER(2,0),
  COMPUTATION_METHOD          NUMBER(2,0),  
  START_DATE                  DATE,
  END_DATE                    DATE,
  NAV_DATE                    DATE,
  NB_SHARES_BUSINESS_PARTNER  NUMBER,
  NB_SHARES_TOTAL             NUMBER,
  NB_DAYS                     NUMBER(10,0),
  NAV                         NUMBER,
  FDG                         NUMBER,
  CDVM                        NUMBER,
  DDG                        NUMBER,
  MCL                        NUMBER,
  FUND_PROMOTER_RETROCESSION NUMBER,
  PNB                        NUMBER,  
  CONSTRAINT PK_CFG_RETRO_FEES_DETAILS PRIMARY KEY (FUND_ID,BUSINESS_PARTNER_ID,BUSINESS_PARTNER_TYPE,COMPUTATION_METHOD,START_DATE,END_DATE,NAV_DATE)
);

--}}SOPHIS_SQL