//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ToolkitEmafi.rc
//
#define IDC_CMD_CmdGenerate             101
#define IDC_CMD_CmdCancel               102
#define IDC_CBO_FOLIO                   103
#define IDC_CMD_Update                  104
#define IDC_CBO_FUND                    104
#define IDC_TXT_START_DATE              105
#define IDC_CMD_Delete                  105
#define IDC_TXT_END_DATE                106
#define IDC_CMD_Up                      106
#define IDC_CMD_Config                  107
#define IDC_CMD_Down                    107
#define IDD_TAB_CONSULTATION            107
#define IDC_TAB_Config                  108
#define IDC_CMD_Add                     108
#define IDD_TAB_INSERTION               108
#define IDC_CBO_Bilan                   109
#define IDD_TAB_HISTO                   109
#define IDC_TXT_Code                    110
#define IDC_CBO_Rubric                  110
#define IDC_TXT_Rubric                  111
#define IDD_CONFIGURATIONOD_DLG         111
#define IDC_CBO_PARENT                  111
#define IDC_LST_RUBRIC                  112
#define IDD_TAB_PARAMETRAGE_OD          112
#define IDC_LST_LABEL                   113
#define IDD_TAB_VALIDATION              113
#define IDC_TXT_Label                   114
#define IDD_DIALOG_ETATREGLEMENTAIRE    114
#define IDC_CHK_Enabled                 115
#define IDC_TXT_AccountDesc             116
#define IDC_CBO_AccountNumber           117
#define IDC_CBO_Label                   118
#define IDC_LST_ACCOUNT                 119
#define IDC_CBO_RubricType              120
#define IDC_TAB_GestionOD               121
#define IDC_CMD_Consult                 122
#define IDC_CMD_Delete_OD               123
#define IDC_LST_OD                      125
#define IDC_TXT_JOURNAL                 126
#define IDC_TXT_PIECE                   127
#define IDC_CBO_SENS                    128
#define IDC_TXT_MONTANT                 129
#define IDC_CBO_TIERS                   130
#define IDC_TXT_COMMENT                 131
#define IDC_DATEVALEUR                  132
#define IDC_LST_ODUPDATE                133
#define IDC_CBO_Type                    134
#define IDC_CBO_DEVISE                  135
#define IDC_CBO_COMMENT                 137
#define IDC_LIST_REPORT                 138
#define IDC_COMBO_FILETYPE              139
#define IDC_LST_ODHISTO                 140
#define IDC_CANCEL_HISTO                141
#define IDC_TAB_Config_OD               142
#define IDC_LST_PARAM                   143
#define IDC_TXT_CODE_COMMENT            144
#define IDC_TXT_DESC_COMMENT            145
#define IDC_CHECK_SIMULATION            146
#define IDC_COMBO_TYPEDATE              147
#define IDC_CMD_Validate_OD             148
#define IDC_CMD_Consult2                149
#define IDC_COMBO_FOND                  150
#define IDC_DATE_CONSULTATION           151
#define IDC_CMD_GENERATEREG             152
#define IDC_LST_REPORT                  153
#define IDC_LST_REPORT_REG              154
#define IDC_LST_REPORT_REG2             155
#define IDC_LST_FUND                    155
#define IDC_COMBO_FILETYPE_REG          157
#define IDC_RADIO_FOLIO                 158
#define IDC_RADIO_FUND                  159
#define IDC_TXT_ACCOUNT_PATTERN         159
#define STR_TAB_RUBRIC                  12976
#define STR_TAB_LABEL                   12977
#define STR_TAB_ACCOUNT                 12978
#define STR_TAB_ODINSERTION             12979
#define STR_TAB_ODCONSULTATION          12980
#define STR_TAB_ODHISTORIQUE            12981
#define MSG_SELECT_REPORT               12981
#define MSG_FILE_GENERATED              12982
#define MSG_ACCESS_DENIED               12983
#define MSG_LINK_REMOVED                12984
#define MSG_NO_SUCCESS                  12985
#define MSG_OD_DELETED                  12986
#define MSG_NO_CHANGES                  12987
#define MSG_ALREADY_DELETED             12988
#define MSG_DELETION_DENIED             12989
#define MSG_FOLIO                       12990
#define MSG_ACCOUNT                     12991
#define MSG_DEBIT_CREDIT                12992
#define MSG_THIRD_PARTY                 12993
#define MSG_AMOUNT                      12994
#define MSG_VALUE_DATE                  12995
#define MSG_CURRENCY                    12996
#define MSG_CLASSIFICATION              12997
#define MSG_SAVING_DONE                 12998
#define MSG_OD_ACCOUNTING               12999
#define MSG_ERROR_OD                    13000
#define MSG_DB_ERROR                    13001
#define MSG_LABEL_DELETED               13002
#define MSG_LABEL_ASK                   13003
#define MSG_FIELD                       13004
#define MSG_CODE                        13005
#define MSG_NO_VALIDATION               13006
#define MSG_SUCCESS_DELETE              13008
#define MSG_DELETE_ASK                  13009
#define MSG_DELETE_RUBRIC               13011
#define MSG_RURIC_LABEL                 13012
#define MSG_RURIC_LABEL2                13012
#define MSG_DELETED_RUBRIC              13013
#define MSG_DELETED_RUBRIC2             13013
#define MSG_OPERATION                   13014
#define MSG_VALIDATION_SUCCESS          13015
#define IDD_DLG_GenerateBilan           52976
#define IDD_DLG_Config                  52977
#define IDD_TAB_Rubric                  52978
#define IDD_TAB_Label                   52989
#define IDD_TAB_Account                 52990
#define IDD_DLG_GestionOd               52991

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        115
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         160
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
