//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace SophisETL.Transform.GroupBySum.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/GroupBySum")]
    [System.Xml.Serialization.XmlRootAttribute("settings", Namespace="http://www.sophis.net/SophisETL/Transform/GroupBySum", IsNullable=false)]
    public partial class Settings {
        
        private GroupByElement[] groupByListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupByList")]
        public GroupByElement[] groupByList {
            get {
                return this.groupByListField;
            }
            set {
                this.groupByListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sophis.net/SophisETL/Transform/GroupBySum")]
    public partial class GroupByElement {
        
        private string groupByFieldField;
        
        private string sumFieldField;
        
        /// <remarks/>
        public string groupByField {
            get {
                return this.groupByFieldField;
            }
            set {
                this.groupByFieldField = value;
            }
        }
        
        /// <remarks/>
        public string sumField {
            get {
                return this.sumFieldField;
            }
            set {
                this.sumFieldField = value;
            }
        }
    }
}
