---------EF_LOGS
CREATE TABLE EF_LOGS
(
  ID        NUMBER,
  DT        TIMESTAMP(6),
  SEVERITY  VARCHAR2(10 BYTE),
  LOGGER    VARCHAR2(255 BYTE),
  MSG       VARCHAR2(4000 BYTE)
);

CREATE UNIQUE INDEX PK_EF_LOGS ON EF_LOGS(ID);
CREATE INDEX IDX_EF_LOGS ON EF_LOGS(LOGGER, DT);
CREATE SEQUENCE EF_LOGS_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE EF_TABLES
(
	TABLE_NAME VARCHAR2(30) NOT NULL
);
CREATE UNIQUE INDEX IDX_EF_TABLES_NAME ON EF_TABLES(TABLE_NAME);

INSERT INTO EF_TABLES(TABLE_NAME) VALUES('EMAFI_CRE');
INSERT INTO EF_TABLES(TABLE_NAME) VALUES('EMAFI_AUDIT_CRE');

CREATE GLOBAL TEMPORARY TABLE EF_TEMPS
(
	CATEGORY VARCHAR2(10),
	STR1 VARCHAR2(255),
	STR2 VARCHAR2(255)
)
ON COMMIT PRESERVE ROWS
NOCACHE;
