CREATE TABLE MAPS
(
	CODE VARCHAR2(5) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	CONTENT CLOB
);
CREATE UNIQUE INDEX PK_MAPS ON MAPS(CODE);

CREATE TABLE MAPS_TABLES
(
    TABLE_NAME VARCHAR2(30) NOT NULL,
    SEQUENCES VARCHAR2(255),
	MAXBY VARCHAR2(255),
	ORDERBY VARCHAR2(255),
	PK_COLUMNS VARCHAR2(255),
	OFF_COLUMNS VARCHAR2(255),
	BK_TABLE_NAME VARCHAR2(30),
	ENABLED CHAR DEFAULT 1 CHECK (ENABLED IN (0,1))
);
CREATE UNIQUE INDEX PK_MAPS_TABLES ON MAPS_TABLES(TABLE_NAME);
CREATE UNIQUE INDEX PK_MAPS_BK_TABLES ON MAPS_TABLES(BK_TABLE_NAME);

CREATE TABLE MAPS_TKT_TABLES
(
    TABLE_NAME VARCHAR2(30) NOT NULL,
    DESCRIPTION VARCHAR2(255),
	SELECTCLAUSE VARCHAR2(255),
	ENABLED CHAR DEFAULT 1 CHECK (ENABLED IN (0,1))
);
CREATE UNIQUE INDEX PK_MAPS_TKT_TABLES ON MAPS_TKT_TABLES(TABLE_NAME);

INSERT INTO MAPS_TKT_TABLES(TABLE_NAME, DESCRIPTION, SELECTCLAUSE) VALUES ('ACCOUNT_RULES', 'Parameter ACCOUNT_RULES', 'SELECT ID, NAME FROM ACCOUNT_RULES WHERE RECORD_TYPE = 1 ORDER BY NAME');
INSERT INTO MAPS_TKT_TABLES(TABLE_NAME, DESCRIPTION, SELECTCLAUSE) VALUES ('EMAFI_REPORT', 'Parameter EMAFI Report', 'SELECT REPORT_TYPE, NAME FROM EMAFI_REPORT ORDER BY ETAT_TYPE, REPORT_ORDER');

CREATE TABLE MAPS_IDS(
    TABLE_NAME VARCHAR2(30) NOT NULL,
    OLD_ID NUMBER(10),
    NEW_ID NUMBER(10)
);

INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_MAP', 'ID@SEQACCOUNT', NULL, 'ACCOUNT_NUMBER, PRIORITY, ACCOUNT_NAME_ID', NULL, 'MAPS_BK_AM_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_RULES', 'ID@SEQACCOUNT', NULL, 'RECORD_TYPE, NAME', 'NAME,RECORD_TYPE', 'MAPS_BK_AR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_POSTING_RULES', 'ID@SEQACCOUNT', NULL, 'PRIORITY', NULL, 'MAPS_BK_APR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_NAME', 'ID@SEQACCOUNT', NULL, 'NAME, ID', NULL, 'MAPS_BK_AN_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_NAME_CATEGORY', NULL, NULL, 'CATEGORY', 'CATEGORY', 'MAPS_BK_ANC_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_POSTING_TYPES', 'ID@SEQ_POSTING_TYPE', NULL, 'ID', 'NAME', 'MAPS_BK_APT_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_BOOK', 'ID@SEQACCOUNT', NULL, 'RECORD_TYPE, NAME, ID', 'NAME,RECORD_TYPE', 'MAPS_BK_AB_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_BOOK_FOLIO', 'ID@SEQACCOUNT', NULL, 'PRIORITY', NULL, 'MAPS_BK_ABF_{TIMESTAMP}', 0);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_ENTITY', 'ID@SEQACCOUNT', NULL, 'RECORD_TYPE, NAME', 'NAME,RECORD_TYPE', 'MAPS_BK_AE_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_ENTITY_RULES', 'ID@SEQACCOUNT', 'PRIORITY@ACCOUNT_ENTITY_ID', 'ACCOUNT_ENTITY_ID, PRIORITY, RULES, ID', NULL, 'MAPS_BK_AER_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_ENTITY_EOD', NULL, NULL, 'ACCOUNT_ENTITY_ID', NULL, 'MAPS_BK_AEE_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_PNL_RULES', 'ID@SEQACCOUNT', NULL, 'RECORD_TYPE, NAME, ID', 'NAME,RECORD_TYPE', 'MAPS_BK_APNR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_PNL_POSTING_RULES', 'ID@SEQACCOUNT', NULL, 'RULE_ID, NAME, PRIORITY, ID', NULL, 'MAPS_BK_APNPR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_BALANCE_RULES', 'ID@SEQACCOUNT', NULL, 'RECORD_TYPE, NAME', 'NAME,RECORD_TYPE', 'MAPS_BK_ABR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_BAL_POSTING_RULES', 'ID@SEQACCOUNT', NULL, 'PRIORITY', NULL, 'MAPS_BK_ABPR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_AMORTIZING_RULES_FIRST', 'ID@SEQACCOUNT', NULL, 'RECORD_TYPE, NAME', 'NAME,RECORD_TYPE', 'MAPS_BK_AARF_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_AMORTIZING_RULES', 'ID@SEQACCOUNT', NULL, 'PRIORITY', NULL, 'MAPS_BK_AAR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_SETT_RULES', 'ID@SEQACCOUNT', NULL, 'RECORD_TYPE, NAME', 'NAME,RECORD_TYPE', 'MAPS_BK_ASR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_SETT_POSTING_RULES', 'ID@SEQACCOUNT', NULL, 'PRIORITY', NULL, 'MAPS_BK_ASPR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_PAYM_RULES', 'ID@SEQACCOUNT', NULL, 'RECORD_TYPE, NAME', 'NAME,RECORD_TYPE', 'MAPS_BK_APAR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_PAYM_POSTING_RULES', 'ID@SEQACCOUNT', NULL, 'PRIORITY', NULL, 'MAPS_BK_APAPR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_DEAL_RULES_FIRST', 'ID@SEQACCOUNT', NULL, 'RECORD_TYPE, NAME', NULL, 'MAPS_BK_ADRF_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_DEAL_RULES', 'ID@SEQACCOUNT', 'PRIORITY@LINK_ID', 'PRIORITY', NULL, 'MAPS_BK_ADR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_AUX_LEDGER_RULES_FIRST', 'ID@SEQACCOUNT', NULL, 'RECORD_TYPE, NAME', NULL, 'MAPS_BK_AALRF_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('ACCOUNT_AUX_LEDGER_RULES', 'ID@SEQACCOUNT', 'PRIORITY@LINK_ID', 'ACCOUNT_ENTITY_ID, LINK_ID, PRIORITY, ID', NULL, 'MAPS_BK_AALR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('BO_ALLOTMENT_GROUPS', NULL, NULL, 'ID', 'ID', 'MAPS_BK_BAG_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('AFFECTATION', NULL, NULL, 'LIBELLE', 'LIBELLE', 'MAPS_BK_A_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('BO_ALLOTMENT_GROUPS_COMPONENTS', NULL, NULL, NULL, 'ID', 'MAPS_BK_BAGC_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('EMAFI_REPORT', NULL, NULL, 'ETAT_TYPE, REPORT_ORDER', 'REPORT_TYPE', 'MAPS_BK_EMAFIR_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('EMAFI_RUBRIC', NULL, NULL, 'REPORT_TYPE, REPORT_ORDER', 'ID', 'MAPS_BK_EMAFIRU_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('EMAFI_LABEL', NULL, NULL, 'ID_RUBRIC, REPORT_ORDER', 'ID', 'MAPS_BK_EMAFIL_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('EMAFI_ACCOUNT', NULL, NULL, 'ID_LABEL, ACCOUNT_NUMBER', 'ID_LABEL, ACCOUNT_NUMBER', 'MAPS_BK_EMAFIA_{TIMESTAMP}', 1);
INSERT INTO MAPS_TABLES(TABLE_NAME, SEQUENCES, MAXBY, ORDERBY, PK_COLUMNS, BK_TABLE_NAME, ENABLED) VALUES('EMAFI_PARAMETRAGE', NULL, NULL, 'CATEGORIE, ORDRE', 'CATEGORIE, CODE', 'MAPS_BK_EMAFIP_{TIMESTAMP}', 1);

CREATE TABLE MAPS_FK
(
	TABLE_NAME VARCHAR2(30) NOT NULL,
	COLUMN_NAME VARCHAR2(30) NOT NULL,
	FK_NAME VARCHAR2(30),
	R_TABLE_NAME VARCHAR2(30) NOT NULL,
	R_COLUMN_NAME VARCHAR2(30) NOT NULL
);

INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_MAP', 'ACCOUNT_NAME_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_POSTING_RULES', 'RULE_ID', NULL, 'ACCOUNT_RULES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_POSTING_RULES', 'ACCOUNT_NAME_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_POSTING_RULES', 'AUXILIARY1_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_POSTING_RULES', 'AUXILIARY2_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_POSTING_RULES', 'AUXILIARY3_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_BOOK_FOLIO', 'ACCOUNT_BOOK_ID', NULL, 'ACCOUNT_BOOK', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_ENTITY_RULES', 'ACCOUNT_ENTITY_ID', NULL, 'ACCOUNT_ENTITY', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_ENTITY_RULES', 'RULES', NULL, 'ACCOUNT_RULES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_ENTITY_RULES', 'RULES', NULL, 'ACCOUNT_BALANCE_RULES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_ENTITY_RULES', 'RULES', NULL, 'ACCOUNT_PAYM_RULES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_ENTITY_RULES', 'RULES', NULL, 'ACCOUNT_PNL_RULES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_ENTITY_RULES', 'RULES', NULL, 'ACCOUNT_SETT_RULES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_ENTITY_EOD', 'ACCOUNT_ENTITY_ID', NULL, 'ACCOUNT_ENTITY', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_NAME', 'CATEGORY', NULL, 'ACCOUNT_NAME_CATEGORY', 'CATEGORY');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PNL_POSTING_RULES', 'RULE_ID', NULL, 'ACCOUNT_PNL_RULES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PNL_POSTING_RULES', 'ACCOUNT_NAME_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PNL_POSTING_RULES', 'AUXILIARY1_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PNL_POSTING_RULES', 'AUXILIARY2_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PNL_POSTING_RULES', 'AUXILIARY3_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PNL_POSTING_RULES', 'POSTING_TYPE', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PAYM_POSTING_RULES', 'RULE_ID', NULL, 'ACCOUNT_PAYM_RULES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PAYM_POSTING_RULES', 'ACCOUNT_NAME_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PAYM_POSTING_RULES', 'AUXILIARY1_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PAYM_POSTING_RULES', 'AUXILIARY2_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PAYM_POSTING_RULES', 'AUXILIARY3_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_PAYM_POSTING_RULES', 'POSTING_TYPE', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_SETT_POSTING_RULES', 'RULE_ID', NULL, 'ACCOUNT_SETT_RULES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_SETT_POSTING_RULES', 'ACCOUNT_NAME_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_SETT_POSTING_RULES', 'AUXILIARY1_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_SETT_POSTING_RULES', 'AUXILIARY2_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_SETT_POSTING_RULES', 'AUXILIARY3_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_SETT_POSTING_RULES', 'POSTING_TYPE', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_BAL_POSTING_RULES', 'RULE_ID', NULL, 'ACCOUNT_BALANCE_RULES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_BAL_POSTING_RULES', 'ACCOUNT_NAME_ID_RECPT', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_BAL_POSTING_RULES', 'ACCOUNT_NAME_ID_SEND', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_BAL_POSTING_RULES', 'POSTING_TYPE_RECEPTION', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_BAL_POSTING_RULES', 'POSTING_TYPE_SEND', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AMORTIZING_RULES', 'RULE_ID', NULL, 'ACCOUNT_AMORTIZING_RULES_FIRST', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AMORTIZING_RULES', 'ACCOUNT_NAME_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_DEAL_RULES', 'LINK_ID', NULL, 'ACCOUNT_DEAL_RULES_FIRST', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_DEAL_RULES', 'ACCOUNT_ENTITY_ID', NULL, 'ACCOUNT_ENTITY', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_DEAL_RULES', 'ACC_PORTFOLIO', NULL, 'ACCOUNT_BOOK', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AUX_LEDGER_RULES', 'LINK_ID', NULL, 'ACCOUNT_AUX_LEDGER_RULES_FIRST', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AUX_LEDGER_RULES', 'ACCOUNT_ENTITY_ID', NULL, 'ACCOUNT_ENTITY', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AUX_LEDGER_RULES', 'ACCOUNT_NAME_ID', NULL, 'ACCOUNT_NAME', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AUX_LEDGER_RULES', 'POSTING_TYPE_CAPITAL_GAIN', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AUX_LEDGER_RULES', 'POSTING_TYPE_CAPITAL_LOSS', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AUX_LEDGER_RULES', 'POSTING_TYPE_ASSET_LONG', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AUX_LEDGER_RULES', 'POSTING_TYPE_ASSET_SHORT', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AUX_LEDGER_RULES', 'POSTING_TYPE', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('ACCOUNT_AUX_LEDGER_RULES', 'POSTING_TYPE_SPLIT', NULL, 'ACCOUNT_POSTING_TYPES', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('BO_ALLOTMENT_GROUPS_COMPONENTS', 'ALLOTMENT_GROUP_COMPONENT_ID', NULL, 'BO_ALLOTMENT_GROUPS', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('BO_ALLOTMENT_GROUPS_COMPONENTS', 'ALLOTMENT_ID', NULL, 'AFFECTATION', 'IDENT');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('EMAFI_RUBRIC', 'REPORT_TYPE', NULL, 'EMAFI_REPORT', 'REPORT_TYPE');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('EMAFI_LABEL', 'ID_RUBRIC', NULL, 'EMAFI_RUBRIC', 'ID');
INSERT INTO MAPS_FK(TABLE_NAME, COLUMN_NAME, FK_NAME, R_TABLE_NAME, R_COLUMN_NAME) VALUES('EMAFI_ACCOUNT', 'ID_LABEL', NULL, 'EMAFI_LABEL', 'ID');

SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK OFF
DECLARE resultStr CLOB;
BEGIN
    DBMS_OUTPUT.ENABLE (buffer_size => NULL);
    DBMS_OUTPUT.PUT_LINE('SET SERVEROUTPUT ON');
    DBMS_OUTPUT.PUT_LINE('SET DEFINE OFF');
    DBMS_OUTPUT.PUT_LINE('TRUNCATE TABLE MAPS_IDS;');
    DBMS_OUTPUT.PUT_LINE('SELECT SEQACCOUNT.NEXTVAL FROM DUAL;');
	EM.GENERATEALL;
    --resultStr := EM.GENERATE_INSERT('BO_ALLOTMENT_GROUPS', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('AFFECTATION', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('BO_ALLOTMENT_GROUPS_COMPONENTS', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_SETT_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_AUX_LEDGER_RULES_FIRST', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_BALANCE_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_PNL_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_NAME_CATEGORY', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_NAME', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_NAME', 'ID = 43216');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_RULES', 'NAME = ''10 - Equity - Purchase_Fees'' AND RECORD_TYPE = 1', true);
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_POSTING_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_POSTING_RULES', 'T.ID = 26369');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_PAYM_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_ENTITY_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_ENTITY', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_ENTITY', 'NAME = ''EMAFI Account Entities_NoFees_Encaisse'' AND RECORD_TYPE = 1', true);
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_POSTING_TYPES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_BAL_POSTING_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_PNL_POSTING_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_AUX_LEDGER_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_NAME', 'ID = 40190');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_MAP', 'ACCOUNT_NUMBER = ''11720--111''');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_POSTING_RULES', '1 = 1');
    --resultStr := EM.GENERATE_INSERT('ACCOUNT_ENTITY_EOD', '1 = 1');
END;
/
