#define	NAME_SIZE						1024
#define QUERY_BUFFER_SIZE				1024
#define REPO_BORROWING_TVA_RATE_ID		17
#define BROKER_FEES_TVA_RATE_ID			12
#define MARKET_FEES_TVA_RATE_ID			13
#define COUNTERPARTY_FEES_TVA_RATE_ID	14